// Generated by scripts/build-issue-data.js from assets/issues. Do not edit by hand.
// Run: node scripts/build-issue-data.js

var ISSUE_DATA = {
  "confessions-of-an-anxious-creator": {
    "title": "confessions of an anxious creator",
    "cover": "assets/issues/confessions of an anxious creator/cover.png",
    "pages": [
      {
        "type": "cover"
      },
      {
        "type": "image",
        "src": "assets/issues/confessions of an anxious creator/page 1.JPG",
        "label": "page 1"
      },
      {
        "type": "image",
        "src": "assets/issues/confessions of an anxious creator/page-2.JPG",
        "label": "page 2"
      },
      {
        "type": "image",
        "src": "assets/issues/confessions of an anxious creator/page-3.JPG",
        "label": "page 3"
      },
      {
        "type": "image",
        "src": "assets/issues/confessions of an anxious creator/page-4.JPG",
        "label": "page 4"
      },
      {
        "type": "image",
        "src": "assets/issues/confessions of an anxious creator/page-5.JPG",
        "label": "page 5"
      },
      {
        "type": "image",
        "src": "assets/issues/confessions of an anxious creator/page-6.JPG",
        "label": "page 6"
      }
    ]
  },
  "idea-marinade": {
    "title": "idea marinade",
    "pages": [
      {
        "type": "cover"
      },
      {
        "type": "image",
        "src": "assets/issues/idea marinade/page-1.jpeg",
        "label": "page 1"
      },
      {
        "type": "image",
        "src": "assets/issues/idea marinade/page-2.jpeg",
        "label": "page 2"
      },
      {
        "type": "image",
        "src": "assets/issues/idea marinade/page-3.jpeg",
        "label": "page 3"
      },
      {
        "type": "image",
        "src": "assets/issues/idea marinade/page-4.jpeg",
        "label": "page 4"
      }
    ],
    "cover": "assets/issues/idea marinade/cover.jpeg"
  },
  "observations-as-an-introvert": {
    "title": "observations as an introvert",
    "pages": [
      {
        "type": "cover"
      },
      {
        "type": "image",
        "src": "assets/issues/observations as an introvert/page-1.jpeg",
        "label": "page 1"
      },
      {
        "type": "image",
        "src": "assets/issues/observations as an introvert/page-2.jpeg",
        "label": "page 2"
      },
      {
        "type": "image",
        "src": "assets/issues/observations as an introvert/page-3.jpeg",
        "label": "page 3"
      },
      {
        "type": "image",
        "src": "assets/issues/observations as an introvert/page-4.jpeg",
        "label": "page 4"
      }
    ],
    "cover": "assets/issues/observations as an introvert/cover.jpeg"
  },
  "romaticise-the-mundane": {
    "title": "romaticise the mundane",
    "pages": [
      {
        "type": "cover"
      },
      {
        "type": "image",
        "src": "assets/issues/romaticise the mundane/page 1.jpeg",
        "label": "page 1"
      },
      {
        "type": "image",
        "src": "assets/issues/romaticise the mundane/page 2.jpeg",
        "label": "page 2"
      },
      {
        "type": "image",
        "src": "assets/issues/romaticise the mundane/page 3.jpeg",
        "label": "page 3"
      },
      {
        "type": "image",
        "src": "assets/issues/romaticise the mundane/page 4.jpeg",
        "label": "page 4"
      },
      {
        "type": "image",
        "src": "assets/issues/romaticise the mundane/page 5.jpeg",
        "label": "page 5"
      }
    ],
    "cover": "assets/issues/romaticise the mundane/cover.png"
  },
  "self-perception": {
    "title": "self-perception",
    "pages": [
      {
        "type": "cover"
      },
      {
        "type": "image",
        "src": "assets/issues/self-perception/page-1.jpeg",
        "label": "page 1"
      },
      {
        "type": "image",
        "src": "assets/issues/self-perception/page-2.jpeg",
        "label": "page 2"
      },
      {
        "type": "image",
        "src": "assets/issues/self-perception/page-3.jpeg",
        "label": "page 3"
      },
      {
        "type": "image",
        "src": "assets/issues/self-perception/page-4.jpeg",
        "label": "page 4"
      }
    ],
    "cover": "assets/issues/self-perception/self-perception-cover page.png"
  },
  "stillherestilllife": {
    "title": "stillherestilllife",
    "pages": [
      {
        "type": "cover"
      },
      {
        "type": "image",
        "src": "assets/issues/stillherestilllife/page-1.jpg",
        "label": "page 1"
      },
      {
        "type": "image",
        "src": "assets/issues/stillherestilllife/page-2.jpg",
        "label": "page 2"
      },
      {
        "type": "image",
        "src": "assets/issues/stillherestilllife/page-3.jpg",
        "label": "page 3"
      },
      {
        "type": "image",
        "src": "assets/issues/stillherestilllife/page-5.png",
        "label": "page 5"
      }
    ],
    "cover": "assets/issues/stillherestilllife/cover.png"
  }
};

function getIssueBySlug(slug) {
  return ISSUE_DATA[slug] || null;
}

/*
 * Homepage sets this right before navigating to issue.html. Static servers (e.g. `serve`) may 301 to a
 * clean URL and drop ?slug=; reading this after load restores the correct issue on L2.
 */
var DIGIZINE_ISSUE_SLUG_STORAGE_KEY = 'digizineIssueSlug';

function setPendingIssueSlug(slug) {
  try {
    if (slug) sessionStorage.setItem(DIGIZINE_ISSUE_SLUG_STORAGE_KEY, slug);
  } catch (e) {}
}

/** Prefer ?slug=, then one-shot sessionStorage from the shelf click. */
function takeIssueSlugForIssuePage() {
  var q = new URLSearchParams(location.search).get('slug');
  if (q) return q;
  try {
    var s = sessionStorage.getItem(DIGIZINE_ISSUE_SLUG_STORAGE_KEY);
    if (s) {
      sessionStorage.removeItem(DIGIZINE_ISSUE_SLUG_STORAGE_KEY);
      return s;
    }
  } catch (e) {}
  return '';
}
